#!/bin/bash

[ -r /etc/lsb-release ] && . /etc/lsb-release

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
        # Fall back to using the very slow lsb_release utility
        DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi

echo
printf "\e[0;90m"
printf "         _"
printf "       /X \ "
printf "     _------_"
printf "    /        \"
printf "   |          |"
printf "   |          |"
printf "   |     __  __)"
printf "   |    /  \/  \"
printf "  /\/\ (o   )o  )"
printf "  /c    \__/ --."
printf "  \_   _-------'"
printf "   |  /         \"
printf "   | | '\________)"
printf "   |  \_____)"
printf "   |_____ |"
printf "  |_____/\/\"
printf "  /        \"
printf ""


printf "  \/________________   \n"
printf " /     _____________)  \n"
printf "/     /     /   \ |    \n"
printf "\/\/\/     (O) (O)|    \n"
printf "  |           ------,  \n"
printf "  |  _       ______/   \n"
printf "  | (_      /   \  \         ******************************************************************************\n"
printf "  |        /  ___\_ \  ___/ *   \e[0;90mRunning \e[0;97m%s\e[0;90m (\e[0;97m%s %s %s\e[0;90m)  *\n" "$DISTRIB_DESCRIPTION" "$(uname -o)" "$(uname -r)" "$(uname -m)"
printf "  |        \      / /     \ *   \e[0;90mToday is \e[0;97m%s %s %s\e[0;90m                                    *\n" "$(date)"
printf "__|_________\______/         ******************************************************************************\n"
printf "\______________\./__\  \n"
printf " /     .       | \  |  \n"
printf " \    /_\   .  |  \ |\ \n"
printf " |.\       /_\  |   \| \ \n"
printf ""
echo
