#!/bin/sh

ppid1=`cat /proc/$PPID/status | grep PPid | awk '{ print $2 }'`
ppid2=`cat /proc/$ppid1/status | grep PPid | awk '{ print $2 }'`
username=`ps -x | grep $ppid2 | awk '{ print $6 }' |  sed "s/[[:digit:].-]//g"`
user=$(whoami)
date=`date`
load=`cat /proc/loadavg | awk '{print $1" (1 minute) "$2" (5 minutes) "$3" (15 minutes)"}'`
root_usage=`df -h / | awk '/\// {print $(NF-1)}'`
root_used=`df -h / | awk '/\// {print $(NF-2)}'`
root_total=`df -h / | awk '/\// {print $(NF-3)}'`
memory_usage=`free | awk '/Mem/{printf("%.1f%"), $3/($2+.000000001)*100} /buffers\/cache/{printf(", buffers: %.1f%"), $4/($3+$4)+.000000001*100} /Swap/{printf(", swap: %.1f%"), $3/($2+.000000001)*100}';`
memory=`free -m | awk '/Mem:/ { print $2 }'`
memory_used=`free -m | awk '/buffers\/cache/ { print $3 }'`
swap_usage=`free -m | awk '/Swap/ { printf("%3.1f%%", "exit !$2;$3/$2*100") }'`
users=`netstat -tnpa | grep 'ESTABLISHED.*sshd' | grep $username | wc -l`
time=`uptime | grep -ohe 'up .*' | sed 's/,/\ hours/g' | awk '{ printf $2" "$3 }'`
processes_total=`ps aux | wc -l`
processes_user=`ps -u $username | wc -l`
ip=`ifconfig $(route | grep default | awk '{ print $8 }') | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}'`
lastlog=`lastlog -u $username | grep -v Latest |  awk '{ printf $5" "$6" "$7" "$9" from "$3 }'`

echo "\e[0;97mLast login: \e[37m"$lastlog
echo "\e[0;97mSSH logins: \e[37m"$users "open sessions"
echo "\e[0;97mUptime: \e[37m""$time"
echo
echo "\e[0;97mSystem load: \e[37m"$load
echo "\e[0;97mMemory usage: \e[37m""$memory_usage"
echo "\e[0;97mHDD usage: \e[37m"$root_used" available / "$root_total "("$root_usage") used"
echo "\e[0;97mProcesses: \e[37m"$processes_total "total," $processes_user "yours"
echo

